#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DigitsDemo.Resource", IsApplication=true)]

namespace DigitsDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int dgts__StateButtonStyle = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int dgts__accentColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int dgts__logoDrawable = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int finishStateText = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int progressStateText = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int startStateText = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int tw__image_aspect_ratio = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int tw__image_dimension_to_adjust = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int dgts__default_accent = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int dgts__default_logo_name = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int dgts__purple = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int dgts__purple_pressed = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int dgts__text_dark = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int dgts__text_light = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int tw__blue_default = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int tw__blue_pressed = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int tw__blue_pressed_light = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int tw__light_gray = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int tw__medium_gray = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int tw__solid_white = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int tw__transparent = 2131230732;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int dgts__country_code_margin_bottom = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int dgts__margin_bottom = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int dgts__padding_container = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int dgts__padding_title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int dgts__permissions_margin_bottom = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int dgts__progress_bar_side_length = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int dgts__terms_text_size = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int dgts__title_text_size = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int tw__btn_bar_margin_left = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int tw__btn_bar_margin_right = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int tw__login_btn_drawable_padding = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int tw__login_btn_height = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int tw__login_btn_left_padding = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int tw__login_btn_radius = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int tw__login_btn_right_padding = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int tw__login_btn_text_size = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int tw__padding_permission_horizontal_container = 2131296269;
			
			// aapt resource value: 0x7f090011
			public const int tw__padding_permission_vertical_container = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int tw__permission_description_text_size = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int tw__permission_title_text_size = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dgts__addressbook_header = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dgts__digits_btn = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dgts__digits_btn_default = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dgts__digits_btn_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dgts__ic_success = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dgts__login_header = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dgts__logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dgts__logo_name = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dgts__spinner_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dgts__spinner_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int progress_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int progress_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tw__ic_logo_default = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tw__login_btn = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int tw__login_btn_default = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tw__login_btn_default_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tw__login_btn_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int tw__login_btn_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tw__login_btn_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int tw__login_btn_pressed_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tw__login_btn_text_color_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tw__share_email_header = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tw__transparent = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001a
			public const int DigitsAuthBtn = 2131361818;
			
			// aapt resource value: 0x7f0a0003
			public const int dgts__confirmationEditText = 2131361795;
			
			// aapt resource value: 0x7f0a0011
			public const int dgts__countryCode = 2131361809;
			
			// aapt resource value: 0x7f0a0004
			public const int dgts__createAccount = 2131361796;
			
			// aapt resource value: 0x7f0a000e
			public const int dgts__dismiss_button = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int dgts__error_text = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int dgts__error_title = 2131361804;
			
			// aapt resource value: 0x7f0a0008
			public const int dgts__find_your_friends = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int dgts__header_image = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int dgts__logo = 2131361808;
			
			// aapt resource value: 0x7f0a0015
			public const int dgts__logo_icon = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int dgts__logo_name = 2131361814;
			
			// aapt resource value: 0x7f0a000a
			public const int dgts__not_now = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int dgts__okay = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public const int dgts__phoneNumberEditText = 2131361810;
			
			// aapt resource value: 0x7f0a0005
			public const int dgts__resendConfirmation = 2131361797;
			
			// aapt resource value: 0x7f0a0013
			public const int dgts__sendCodeButton = 2131361811;
			
			// aapt resource value: 0x7f0a0017
			public const int dgts__state_button = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int dgts__state_progress = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int dgts__state_success = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int dgts__termsText = 2131361812;
			
			// aapt resource value: 0x7f0a0006
			public const int dgts__termsTextCreateAccount = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int dgts__titleText = 2131361794;
			
			// aapt resource value: 0x7f0a000f
			public const int dgts__try_another_phone = 2131361807;
			
			// aapt resource value: 0x7f0a0009
			public const int dgts__upload_contacts = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int height = 2131361792;
			
			// aapt resource value: 0x7f0a001d
			public const int imageView = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int tw__allow_btn = 2131361824;
			
			// aapt resource value: 0x7f0a001f
			public const int tw__not_now_btn = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public const int tw__share_email_desc = 2131361822;
			
			// aapt resource value: 0x7f0a001c
			public const int tw__spinner = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int tw__web_view = 2131361819;
			
			// aapt resource value: 0x7f0a0001
			public const int width = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dgts__activity_confirmation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dgts__activity_contacts = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dgts__activity_failure = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dgts__activity_phone_number = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dgts__activity_pin_code = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int dgts__country_row = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dgts__state_button = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Main = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int tw__activity_oauth = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int tw__activity_share_email = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int tw__cacerts = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060030
			public const int app_name = 2131099696;
			
			// aapt resource value: 0x7f060000
			public const int dgts__call_me = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dgts__calling = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dgts__confirmation_code = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dgts__confirmation_edit_hint = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int dgts__confirmation_error = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int dgts__confirmation_error_alternative = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int dgts__confirmation_expired = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int dgts__continue = 2131099655;
			
			// aapt resource value: 0x7f060029
			public const int dgts__country_spinner_format = 2131099689;
			
			// aapt resource value: 0x7f060008
			public const int dgts__digits_logo_desc = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int dgts__digits_logo_name_desc = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int dgts__dismiss = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int dgts__done = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int dgts__email_request_edit_hint = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int dgts__email_request_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int dgts__find_your_friends = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int dgts__image_header_description = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int dgts__invalid_email = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int dgts__login_digits_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int dgts__network_error = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int dgts__not_now = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int dgts__okay = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int dgts__phone_number_edit_hint = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int dgts__phone_number_text = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int dgts__pin_code_verification_title = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int dgts__resend_confirmation_text = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int dgts__sending = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int dgts__success_desc = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int dgts__terms_email_request = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int dgts__terms_text = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int dgts__terms_text_call_me = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int dgts__terms_text_create = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int dgts__terms_text_sign_in = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int dgts__try_again = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int dgts__try_again_confirmation = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int dgts__try_again_email = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int dgts__try_again_phone_number = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int dgts__try_another_phone = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int dgts__unsupported_operator_error = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int dgts__upload_contacts = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int dgts__verification_code = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int dgts_pin_code_terms = 2131099688;
			
			// aapt resource value: 0x7f060031
			public const int fabric_consumer_key = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int fabric_consumer_secret = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int kit_name = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int tw__allow_btn_txt = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int tw__login_btn_txt = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int tw__not_now_btn_txt = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int tw__share_email_desc = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int tw__share_email_title = 2131099694;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Digits_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int dgts__ButtonText = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int dgts__Container = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int dgts__HeaderMargin = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int dgts__Terms = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int dgts__Title = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tw__Button = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int tw__Button_Light = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int tw__ButtonBar = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tw__Permission_Container = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int tw__Permission_Description = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int tw__Permission_Title = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] StateButton = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 3
			public const int StateButton_dgts__StateButtonStyle = 3;
			
			// aapt resource value: 0
			public const int StateButton_finishStateText = 0;
			
			// aapt resource value: 1
			public const int StateButton_progressStateText = 1;
			
			// aapt resource value: 2
			public const int StateButton_startStateText = 2;
			
			public static int[] tw__AspectRatioImageView = new int[]
			{
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int tw__AspectRatioImageView_tw__image_aspect_ratio = 0;
			
			// aapt resource value: 1
			public const int tw__AspectRatioImageView_tw__image_dimension_to_adjust = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
